### ISSUE TITLE
loadFont doesn't work

### ISSUE THREAD

**Issue by willross** [lazarofl/svg-captcha-express#2]
TypeError: svgCaptchaExpress.loadFont is not a function

This error doesn't exist in the original svg-captcha.

**Comment by lazarofl** [comment]
Nice @noiboi, you're right.

I fixed this issue on 6af4e65. Please update it to version `^1.0.3`

To use it:

```
const captcha = require('svg-captcha-express').create({ 
    cookie: captchaSessionId
})

//load custom font (optional)   
captcha.loadFont(path.join(__dirname, '../fonts/airstrike.ttf'))
```
