### ISSUE TITLE
Why no createMathExpr?

### ISSUE THREAD

**Issue by willross** [lazarofl/svg-captcha-express#3]
createMathExpr is a useful feature, why was it scrapped in this version?

**Comment by lazarofl** [comment]
I agree with you, I'll put this on to-do itens and PRs would be nice too.

**Comment by cmd430** [comment]
I wrote a version of this that just wraps the original package [svg-captcha](https://github.com/lemonce/svg-captcha) 
that supports the math expression captcha and correctly colors the noise lines based on color setting

you can find it here: [cmd430/express-svg-captcha](https://github.com/cmd430/express-svg-captcha)
or via npm with `npm i express-svg-captcha`

**Comment by lazarofl** [comment]
Add support to math expressions on new version 1.0.4 - https://github.com/lazarofl/svg-captcha-express/commit/ecbb39c215ae25da7468779d917f30d5ca454fe9
