### ISSUE TITLE
airstrike font is not case sensitive

### ISSUE THREAD

**Issue by joeywcl** [lazarofl/svg-captcha-express#4]
Hi, I believe the font used in 
https://github.com/lazarofl/svg-captcha-express/blob/d2b71351cf954acac84f1a41a21859f41ca29552/test/server.js#L19
is not case sensitive as it outputs the image in capital letters only despite the captcha.text output is "MFsN"
![image](https://user-images.githubusercontent.com/27674401/43444902-811c24e2-94d7-11e8-9d1d-9214960bb609.png)

Running server.js will be always returned the validation checks as false. 

Comismsh.ttf however has no issues.

**Comment by lazarofl** [comment]
Nice suggestion @joeywcl,

If it's possible, send a PR with that change and I'll merge it and update the lib.

**Comment by lazarofl** [comment]
Closed 🚀
